version: '3.8'
services:

  # Application
  app:
    container_name: app
    build:
      context: .
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - "db"

  # Web Server
  web:
    container_name: web
    build:
      context: .
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - "app"
    ports:
      - "80:80"
      - "3000:3000"

  # Database
  db:
    container_name: db
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"

volumes:
  dbdata: